// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR88buATStPm2f2GMuyQnXJ5z7G97wLYU',
    appId: '1:101045364723:web:80c515a459aa1726a65486',
    messagingSenderId: '101045364723',
    projectId: 'appteachers-5a050',
    authDomain: 'appteachers-5a050.firebaseapp.com',
    storageBucket: 'appteachers-5a050.appspot.com',
    measurementId: 'G-WW3THB1T5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA40L-G9qj__FOvNtljoIfwdrQTfYOUdxc',
    appId: '1:101045364723:android:ee578643199a4774a65486',
    messagingSenderId: '101045364723',
    projectId: 'appteachers-5a050',
    storageBucket: 'appteachers-5a050.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ3WBIaWSrZ5xMDmdqLpVFdbkkMbCcc_I',
    appId: '1:101045364723:ios:b71fbd47e3b2f2eea65486',
    messagingSenderId: '101045364723',
    projectId: 'appteachers-5a050',
    storageBucket: 'appteachers-5a050.appspot.com',
    iosBundleId: 'com.example.preppaProfesores',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ3WBIaWSrZ5xMDmdqLpVFdbkkMbCcc_I',
    appId: '1:101045364723:ios:b71fbd47e3b2f2eea65486',
    messagingSenderId: '101045364723',
    projectId: 'appteachers-5a050',
    storageBucket: 'appteachers-5a050.appspot.com',
    iosBundleId: 'com.example.preppaProfesores',
  );
}
